DROP TABLE verbruik;
DROP TABLE materiaal;
DROP TABLE uren;
DROP TABLE locatie;
DROP TABLE rating;
DROP TABLE taak;
DROP TABLE fase;
DROP TABLE project;
DROP TABLE klant;
DROP TABLE contract;
DROP TABLE contract_type;
DROP TABLE verlof;
ALTER TABLE medewerker DROP CONSTRAINT fk_service_area_naam;
DROP TABLE service_area;
DROP TABLE medewerker;